### ISSUE TITLE
Openstack / Glance provider

### ISSUE THREAD

**Issue by arthurlogilab** [andsens/bootstrap-vz#185]
This is a feature request for an openstack / glance provider. 

From what I've read in the source could, this would probably be similar to the GSE UploadImage, generate an raw kvm+virtio image and then do glance upload with the correct parameters and credentials.

**Comment by olberger** [comment]
I'm not sure I understand the original request, but wouldn't it be enough to configure the cloud-init plugin for OpenStack ?

Thanks in advance.

**Comment by olberger** [comment]
I've made some tests, and it seems that adding the cloud-init plugin would be enough, provided that the metadata sources are configured correctly. For instance:
```
plugins:
  root_password:
    password: whatever
  cloud_init:
    username: debian
    metadata_sources: NoCloud, ConfigDrive, OpenStack, Ec2
```
Note that the 'OpenStack' camel case is important, for it to work (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841315 for some context).
