### ISSUE TITLE
Partitionning: manage any mount point & mount options

### ISSUE THREAD

**Issue by josqu4red** [andsens/bootstrap-vz#244]
For instance: it is rather common to put /tmp on a dedicated partition and with noexec/nodev/nosuid mount options.
Not being limited to root/boot/swap partitions would be nice; definitions could be like:
```yaml
partitions:
  /tmp:
    filesystem: ext4
    size: 1GiB
    mount_options: defaults,nodev,noexec,nosuid
```
or with a ```mount_point``` key to keep a sane name.

Thanks in advance
