### ISSUE TITLE
Fails to unmount /proc

### ISSUE THREAD

**Issue by sebastinas** [andsens/bootstrap-vz#302]
When trying to create a jessie image bootstrap-vz fails at the end with:
```
[1923699.63694] DEBUG: Executing: umount /opt/bootstrap-vz/88d408db/root/proc
[1923702.44503] ERROR: umount: /opt/bootstrap-vz/88d408db/root/proc: target is busy
[1923702.60501] ERROR: (In some cases useful info about processes that
[1923702.66891] ERROR: use the device is found by lsof(8) or fuser(1).)
```
The problem seems to be that binfmt_misc is still mounted `/opt/bootstrap-vz/88d408db/root/proc/sys/fs/binfmt_misc` at this point. I'm not sure why binfmt_misc is mounted. The only occurrence I could find is in systemd automount targets.

This is my manifest:
```yml
---
name: ITS-2016-{system.release}-{system.architecture}-{%y}{%m}{%d}

provider:
  name: virtualbox
  guest_additions: /usr/share/virtualbox/VBoxGuestAdditions.iso

bootstrapper:
  workspace: /opt/bootstrap-vz

image:
  name: debian-{system.release}-{system.architecture}-{%y}{%m}{%d}
  description: Debian {system.release} {system.architecture}

system:
  release: jessie
  architecture: amd64
  bootloader: grub
  charmap: UTF-8
  hostname: its-2016
  locale: en_US
  timezone: Europe/Vienna

volume:
  backing: vmdk
  partitions:
    type: msdos
    root:
      filesystem: ext4
      size: 10GB

packages:
  mirror: http://httpredir.debian.org/debian

  sources:
    backports:
      - deb http://httpredir.debian.org/debian jessie-backports main

  install_standard: false
  install:
  - cmake
  - debian-goodies
  - eclipse-cdt
  - g++
  - gdb
  - git
  - gitg
  - gtk3-engines-oxygen
  - htop
  - meld
  - task-xfce-desktop
  - valgrind
  - zsh
  - doxygen
  - octave

plugins:
  admin_user:
    username: its2016

  minimize_size:
    zerofree: true

  unattended_upgrades:
    update_interval: 3
    upgrade_interval: 3

    # “Almost never” download non-security updates
    download_interval: 1000
```

Please let me know if you need any other info.
