### ISSUE TITLE
Add ability use profile rather than creds in EC2 manifest.

### ISSUE THREAD

**Issue by CMeza99** [andsens/bootstrap-vz#420]
The ec2 provider requires the access id and secret:

```yaml
---
provider:
  name: ec2
  credentials:
    access-key: AFAKEACCESSKEYFORAWS
    secret-key: thes3cr3tkeyf0ryourawsaccount/FS4d8Qdva
```

This is not safe for version control and does not account for AWS STS when multifactor auth is used. Being able to define a profile name here that would be defined in ~/.aws/config would help.
