### ISSUE TITLE
Default `minimize_size` settings for Docker

### ISSUE THREAD

**Issue by CMeza99** [andsens/bootstrap-vz#457]
To be inline with https://github.com/moby/moby/blob/e2e5d4bc9da5ba17bb2822909611f8300fdd80f0/contrib/mkimage/debootstrap, I think these settings should be the default for the Docker provider.

```yml
plugins:
  minimize_size:
    apt:
      autoclean: true
      languages: [none]
      gzip_indexes: true
      autoremove_suggests: true
```

I am willing to implement this, but I am not sure the best way to go about it.
