### ISSUE TITLE
Correct syntax for mount_opts

### ISSUE THREAD

**Issue by kevin-olbrich** [andsens/bootstrap-vz#484]
Hi!

I would like to build images with discard mount option set.

Is this the correct syntax? Python code uses list but I am not familiar with yaml:

```
    root:
      filesystem: ext4
      size: 13GiB
      mount_opts:
        - defaults
        - discard
```

**Comment by andsens** [comment]
Yup. No need to worry though, your manifest is checked with a json schema before it is executed. Most errors like these are caught very early in the process.

p.s.: I actually think all datatypes in the manifest are validated, it's only when we get to how options can be used together that we get into uncertain territory, but even there we have the escape hatch of validating with code :-)

**Comment by kevin-olbrich** [comment]
```
volume:
  backing: qcow2
  partitions:
    type: gpt
    boot:
      filesystem: ext4
      size: 1GiB
      mount_opts:
        - defaults
        - discard
    swap:
      size: 2GiB
      mount_opts:
        - sw
        - discard
    root:
      filesystem: ext4
      size: 7GiB
      mount_opts:
        - defaults
        - discard
    var/log:
      filesystem: ext4
      size: 5GiB
      mount_opts:
        - defaults
        - discard
```

> bootstrapvz.common.exceptions.ManifestError: {'backing': 'qcow2', 'partitions': {'type': 'gpt', 'boot': {'filesystem': 'ext4', 'mount_opts': ['defaults', 'discard'], 'size': '1GiB'}, 'swap': {'mount_opts': ['sw', 'discard'], 'size': '2GiB'}, 'root': {'filesystem': 'ext4', 'mount_opts': ['defaults', 'discard'], 'size': '7GiB'}, 'var/log': {'filesystem': 'ext4', 'mount_opts': ['defaults', 'discard'], 'size': '5GiB'}}} is not valid under any of the given schemas
